---
title: "付録"
author: "Yutaka Kuroki"
date: "2017年11月15日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE,
                      include=FALSE)
```

```{r library, include=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(arules)
library(DT)
#options(mc.cores = parallel::detectCores()-1)
#rstan_options(auto_write = TRUE)
```





```{r data_lab, include=FALSE, eval=TRUE}
receipt <- read_csv("E:/Git/DataAnalysis2017/data/receipt_henpin_syori_fin.csv")

customer <- read_csv("E:/Git/DataAnalysis2017/data/customer_2.csv")


store <- read_csv("E:/Git/DataAnalysis2017/data/store_1.csv")

staff <- read_csv("E:/Git/DataAnalysis2017/data/staff_1.csv") 

product <- read_csv("E:/Git/DataAnalysis2017/data/product_2.csv") 

line <- read_csv("E:/Git/DataAnalysis2017/data/line_henpin_syori_fin.csv") %>% 
  mutate(product_id = as.character(product_id))
```

```{r data_for_arules}
data <- line %>% 
  left_join(product, by="product_id") %>% 
  select(receipt_id, category_2) %>% 
  group_by(receipt_id, category_2) %>% 
  summarise(n=n()) %>% 
  spread(category_2, n, fill=0) %>% 
  ungroup() %>% 
  select(-receipt_id) %>% 
  as.matrix()
```

# 第2カテゴリごと

```{r apriori, include=FALSE}
rules <- apriori(data,
        parameter=list(support=0.03, confidence=0.15))
```

```{r rules, include=FALSE}
supp <- inspect(sort(rules, by="support")) %>% head(20)
conf <- inspect(sort(rules, by="confidence")) %>% head(20)
lift <- inspect(sort(rules, by="lift")) %>% head(20)
```

## support TOP20

```{r ,include=TRUE}
supp %>% kable()
```

## confidence TOP20

```{r,include=TRUE}
conf %>% kable()
```

## lift TOP20

```{r,include=TRUE}
lift %>% kable()
```

# 商品ごと

```{r product_for_arules}
data <- line %>% 
  left_join(product, by="product_id") %>% 
  select(receipt_id, product_name) %>% 
  group_by(receipt_id, product_name) %>% 
  summarise(n=n()) %>% 
  spread(product_name, n, fill=0) %>% 
  ungroup() %>% 
  select(-receipt_id) %>% 
  as.matrix()
```

```{r , include=FALSE}
rules <- apriori(data,
        parameter=list(support=0.03, confidence=0.15))
```

```{r , include=FALSE}
supp <- inspect(sort(rules, by="support")) %>% head(20)
conf <- inspect(sort(rules, by="confidence")) %>% head(20)
lift <- inspect(sort(rules, by="lift")) %>% head(20)
```

## support TOP20

```{r ,include=TRUE}
supp %>% kable()
```

## confidence TOP20

```{r,include=TRUE}
conf %>% kable()
```

## lift TOP20

```{r,include=TRUE}
lift %>% kable()
```
