---
title: "geo2"
author: "Yutaka Kuroki"
date: "2018年2月5日"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# library

```{r}
library(tidyverse)
library(lubridate)
```

# data import

```{r data_lab, include=FALSE, eval=TRUE}
# 配布されたデータセット
receipt <- read_csv("E:/Git/DataAnalysis2017/data/receipt_henpin_syori_fin.csv")

customer <- read_csv("E:/Git/DataAnalysis2017/data/customer_2.csv")
customer<- receipt %>% 
  filter(customer_id != -1) %>% 
  group_by(year=year(dt), month=month(dt), customer_id) %>% 
  summarise() %>% 
  ungroup() %>% 
  group_by(customer_id) %>% 
  summarise(count = n()) %>% 
  filter(count > 1) %>% 
  select(-count) %>% 
  mutate(repeater = TRUE) %>% 
  right_join(customer, by="customer_id") %>% 
  replace_na(list(repeater=FALSE)) %>% 
  select(customer_id, repeater, sex, birth_age, comment, visit_interval, zip_code) %>% 
  filter(is.na(comment) == TRUE)

store <- read_csv("E:/Git/DataAnalysis2017/data/store_1.csv")

staff <- read_csv("E:/Git/DataAnalysis2017/data/staff_1.csv") %>% 
  rename(store_id = store_id_num)

product <- read_csv("E:/Git/DataAnalysis2017/data/product_2.csv")

line <- read_csv("E:/Git/DataAnalysis2017/data/line_henpin_syori_fin.csv") %>% 
  mutate(product_id = as.character(product_id)) %>% 
  left_join(receipt %>% select(dt,receipt_id, customer_id, regi_staff), 
            by="receipt_id") %>% 
  left_join(customer %>% select(customer_id, comment),
            by="customer_id") %>% 
  left_join(product %>% select(product_id, product_name),
            by="product_id")
```

```{r}
geo_customer.tmp <- read_csv("data/geo_customer.csv")
station.tmp <- read_csv("data/station20171109free.csv")
ken_all <- read.csv("data/ken_all.csv", fileEncoding = "shift-jis", stringsAsFactors = FALSE) %>% 
  as_tibble()
```

# 関東圏に絞る

```{r}
station <- station.tmp %>% 
  as_tibble() %>% 
  mutate(zipcode = as.integer(str_replace(post,"-",""))) %>% 
  left_join(ken_all, by = "zipcode") %>% 
  filter(l == "東京都"|
           l == "神奈川県"|
           l == "埼玉県"|
           l == "千葉県"|
           l == "栃木県"|
           l == "茨城県"|
           l == "群馬県") %>% 
  select(station_cd, station_g_cd, station_name, line_cd, zipcode, l, m, s, lon, lat)
```

```{r}
geo_customer <- geo_customer.tmp %>% 
  left_join(ken_all, by = "zipcode") %>% 
  filter(l == "東京都"|
           l == "神奈川県"|
           l == "埼玉県"|
           l == "千葉県"|
           l == "栃木県"|
           l == "茨城県"|
           l == "群馬県") %>% 
  select(customer_id, zipcode, lon, lat, l, m, s, repeater)
```



```{r}
# 
tmp <- geo_customer %>%
  mutate(a = 1) %>% 
  left_join(station %>% mutate(a=1) %>% select(-l, -m, -s) , by = "a")

tmp2 <- tmp %>% 
  mutate(dist = sqrt((lon.x-lon.y)^2 + (lat.x-lat.y)^2)) %>% 
  group_by(customer_id) %>% 
  filter(dist == min(dist)) %>% 
  select(customer_id, zipcode = zipcode.x, lon = lon.x, lat = lat.x, station_cd, station_name, line_cd, l, m, s, dist, repeater) %>% 
  left_join(route %>% select(line_cd, line_name), by = "line_cd") %>% 
  arrange(customer_id) %>% 
  select(customer_id, zipcode, lon, lat, station_cd, station_name, line_name, line_cd, l, m, s, dist, repeater)

tmp2 %>% 
  write_csv("data/station_customer.csv")

```

```{r}
tmp2 <- tmp2 %>% group_by(customer_id, l, m, station_name, repeater) %>% summarise()
tmp3 <- line %>% 
  left_join(product %>% select(-in_tax), by = "product_id") %>% 
  left_join(tmp2, by = "customer_id") %>% 
  select(category_1, category_id_1, station_name, l, m, in_tax, repeater)

tmp3 %>% 
  group_by(category_1, l) %>% 
  summarise(sales = sum(in_tax)) %>% 
  ggplot(aes(category_1, sales))+
  geom_bar(stat="identity")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~l, scale="free")

tmp4 <- tmp3 %>% 
  filter(m == "世田谷区"|m=="葛飾区"| m=="渋谷区") %>% 
  group_by(category_1, m, repeater) %>% 
  summarise(sales = sum(in_tax)) %>% 
  spread(m,sales) 
tmp4[is.na(tmp4)] <- 0
tmp4 %>% 
  gather(m,sales,-category_1, -repeater) %>% 
  ggplot(aes(category_1, sales, group=m, fill=repeater))+
  geom_bar(stat="identity")+
  facet_wrap(~m, scale="free")
```

