---
title: "report2"
author: "Yutaka Kuroki"
date: "2018年2月11日"
output: 
  html_document:
    toc: true
    toc_depth: 3
    number_section: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      cache = TRUE)
```

```{r library}
library(tidyverse)
library(lubridate)
library(prophet)
library(knitr)
```


```{r data import, include=FALSE}
setwd("E:/Git/DataAnalysis2017")
receipt <- read_csv("data/receipt_henpin_syori_fin.csv")
store <- read_csv("data/store_1.csv")
weather <- read_csv("data/weather.csv") %>% 
  mutate(dt = as_date(Date),
         rain = log1p(rain)) %>% 
  select(dt, rain, pref)
date <- read_csv("data/date.csv")
```

```{r holiday data, include=FALSE, eval=FALSE}
date <- read_csv("E:/Git/RC/data/date_info.csv")
dt <- tibble(dt = seq(as_date("2015-07-01"), as_date("2017-06-30"), by = "d")) %>% 
  full_join(date %>% select(dt=calendar_date, holiday=holiday_flg), by = "dt")

holiday <- tibble(dt = as_date(c("2015-07-20",
                                 "2015-09-21",
                                 "2015-09-23",
                                 "2015-10-12",
                                 "2015-11-03",
                                 "2015-11-23",
                                 "2015-12-23",
                                 "2015-12-30",
                                 "2015-12-31")),
                  holiday=1)


tmp <- date %>% 
  select(dt = calendar_date,
         holiday = holiday_flg) %>% 
  bind_rows(holiday) %>% 
  arrange(dt) %>% 
  right_join(tibble(dt = seq(as_date("2015-07-01"), as_date("2017-06-30"), by = "d")),
             by = "dt") %>% 
  replace_na(list(holiday=0))

tmp2 <- tmp %>% 
  mutate(year = year(dt),
         month = month(dt),
         day = day(dt),
         wday = wday(dt)-1,
         weekday = as.numeric(wday<6 & wday>0),
         D1 = as.numeric(weekday==1 & holiday==1), # 平日かつ祝日
         holiday_lead = lead(holiday), # 祝前日
         D2 = as.numeric(0<wday & wday<5 & holiday_lead==1)) %>% 
  select(-holiday_lead, -weekday, -holiday, -year, -month, -day)
write_csv(tmp2, "data/date.csv")
```


# 全店舗の需要予測

まずはベースのデータ。明らかにおかしい外れ値除去

```{r all_sales}
all.tmp <- receipt %>% 
  group_by(dt) %>% 
  summarise(sales = sum(in_tax))

all.tmp %>% 
  ggplot(aes(dt,sales))+
  geom_point()

all <- all.tmp %>% 
  filter(sales > 500000)

all %>% 
  ggplot(aes(dt, sales))+
  geom_point()
```

```{r regressor}
weather_all <- weather %>% 
  spread(pref, rain) %>% 
  mutate(rain = (tokyo+yokohama)/2) %>% 
  select(dt, rain)

data_all <- all %>% 
  right_join(date, by = "dt") %>%
  left_join(weather_all, by = "dt")

h <- data_all %>% 
  filter(D1==1 | D2==1) %>% 
  select(dt, D1, D2) %>% 
  gather(holiday,value, -dt) %>% 
  filter(value != 0) %>% 
  mutate(upper_window = 0,
         lower_window = 0) %>% 
  select(holiday, ds = dt, upper_window, lower_window)
```


```{r prophet_all, include=FALSE}
df_all <- data_all %>% 
  mutate(sales = log(sales)) %>% 
  select(ds = dt, y = sales, rain) %>% 
  drop_na() 
m_all <- prophet(yearly.seasonality = TRUE,
                 weekly.seasonality = TRUE,
                 holidays=h) %>% 
  add_regressor("rain") %>% 
  fit.prophet(df_all)
future_all <- make_future_dataframe(m_all, 30) %>% 
  left_join(weather_all %>% mutate(dt = as_datetime(dt)), by = c("ds" = "dt")) %>% 
  replace_na(list(rain=0))
forecast_all <- predict(m_all, future_all) %>% 
  as_tibble() %>% 
  mutate(ds = as_date(ds)) %>% 
  left_join(df_all, by = "ds") %>% 
  mutate(resid = y - yhat)
```

# 店舗別

```{r prophet_store, include=FALSE}
df_store <- receipt %>% 
  group_by(store_id, dt) %>% 
  summarise(sales = log(sum(in_tax))) %>% 
  rename(ds = dt, y = sales) %>% 
  left_join(weather_all, by = c("ds"="dt")) %>% 
  nest()

fit.prophet <- df_store %>% 
  mutate(m = map(data, 
                 ~ prophet(yearly.seasonality = TRUE,
                           weekly.seasonality = TRUE,
                           holidays = h) %>% 
                   add_regressor("rain") %>% 
                   fit.prophet(.x)),
         future = map(m, 
                      ~ make_future_dataframe(.x,30) %>% 
                        left_join(weather_all %>% mutate(dt = as_datetime(dt)), by = c("ds" = "dt")) %>% 
                        replace_na(list(rain=0))),
         forecast = map2(m, future,
                         ~ predict(.x,.y)))
```



```{r result}
result <- fit.prophet %>% 
  mutate(forecast = map2(forecast, data,
                         ~ .x %>% 
                           mutate(ds = as_date(ds)) %>% 
                           left_join(.y, by = "ds"))) %>% 
  select(store_id, forecast) %>% 
  unnest() %>% 
  rename(rain = rain.y, rain_coef = rain.x) %>% 
  mutate(resid = y - yhat) %>% 
  drop_na()
```

# 結果をイジイジ

## 全体

```{r}


forecast_all %>% 
  select(y, yhat) %>% 
  drop_na() %>% 
  cor()
-.961^2

forecast_all %>% 
  ggplot(aes(yhat, y))+
  geom_point()
```


## 店舗別


```{r}
result %>% 
  group_by(store_id) %>% 
  summarise(rmse = sqrt(mean(resid^2)),
            scale = median(trend),
            rmse_rate = rmse/scale,
            rhat = cor(yhat, y)^2) %>% 
  left_join(store %>% select(store_id, store_name),
            by = "store_id") %>% 
  arrange(rmse_rate) %>% 
  mutate(rank_rmse = rank(rmse),
         rank_rhat = rank(desc(rhat))) %>% 
  kable()
```


```{r weekly}
result %>% 
  mutate(wday = wday(ds)) %>% 
  filter(wday != 3) %>% 
  group_by(store_id, wday) %>% 
  summarise(weekly = median(weekly)) %>% 
  ggplot(aes(wday, weekly))+
  geom_bar(stat="identity")+
  facet_wrap(~store_id)


weekly <- result %>% 
  mutate(wday = wday(ds)) %>% 
  group_by(store_id, wday) %>% 
  summarise(weekly = median(weekly)) %>% 
  left_join(store %>% select(store_id, store_name), 
            by = "store_id") %>% 
  ungroup() %>% 
  select(-store_id) %>% 
  spread(store_name, weekly) %>% 
  mutate(theta = seq(0, 2*pi, length.out = 8)[1:7],
         sin = sin(theta),
         cos = cos(theta))


weekly_circle <- weekly %>% 
  select(theta:cos) %>% 
  mutate(wday = 1:n())

weekly %>% 
  select(1:13) %>% 
  gather(store_name, value, -wday) %>% 
  left_join(weekly_circle, by = "wday") %>% 
  mutate(x = value * cos,
         y = value * sin) %>% 
  group_by(store_name) %>% 
  summarise(x = mean(x,na.rm=TRUE),
            y = mean(y, na.rm=TRUE),
         dist = sqrt(x^2 + y^2)) %>% 
  ggplot(aes(x/dist,y/dist))+
  geom_text(aes(label=store_name))+
  scale_x_continuous(limits=c(-1,1))+
  scale_y_continuous(limits=c(-1,1))
```


```{r yearly}
result %>% 
  select(store_id, ds, yearly) %>% 
  ggplot(aes(ds, yearly))+
  geom_line()+
  facet_wrap(~store_id)
  

```


```{r rain_coef}
result %>% 
  select(store_id, ds, rain_coef) %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(ds, rain_coef, group=store_name))+
  geom_line()+
  facet_wrap(~store_name)
```

```{r trend}
result %>% 
  select(store_id, ds, trend) %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(ds, trend, group=store_name))+
  geom_line()+
  theme_bw()+
  facet_wrap(~store_name)
```

```{r trend_obz}
result %>% 
  select(store_id, ds, trend, y) %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(ds, trend))+
  geom_line(aes(y=y))+
  geom_line(colour="red", size=1)+
  theme_bw()+
  facet_wrap(~ store_name)
```

```{r resid}
result %>% 
  select(store_id, ds, resid) %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(ds, resid))+
  geom_line()+
  facet_wrap(~ store_name)
```


```{r y_yhat}
result %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(y, yhat))+
  geom_point()+
  geom_abline(colour="red", size=1)+
  facet_wrap(~store_name, scale="free")
```


```{r acf}

result %>% 
  select(store_id, resid) %>% 
  drop_na() %>% 
  group_by(store_id) %>% 
  nest() %>% 
  mutate(acf = map(data,
                   ~ acf(.x$resid, plot=FALSE, lag.max=27)$acf[,,]),
         pacf = map(data,
                    ~ pacf(.x$resid, plot=FALSE, lag.max=28)$acf[,,])) %>% 
  select(store_id, acf, pacf) %>% 
  unnest() %>% 
  group_by(store_id) %>% 
  mutate(index = 1:n()) %>% 
  left_join(store, by = "store_id") %>% 
  ggplot(aes(index, acf))+
  geom_bar(stat="identity", width=0.7)+
  geom_line(aes(y = pacf), colour="blue")+
  theme_bw()+
  facet_wrap(~store_name)
```
